# Generated by Django 2.0.7 on 2021-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='approval',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='stockrequesthistory',
            name='approval',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
