# Generated by Django 3.1.3 on 2020-12-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequesthistory',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockrequesthistory',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
