# Generated by Django 3.1.3 on 2020-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_auto_20201221_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='approval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockrequesthistory',
            name='approval',
            field=models.CharField(max_length=10),
        ),
    ]
