# Generated by Django 2.0.7 on 2021-01-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_auto_20210104_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='approval',
            field=models.CharField(blank=True, default='Pending', max_length=10),
        ),
    ]
