# Generated by Django 2.0.7 on 2021-01-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_auto_20210126_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequesthistory',
            name='approval',
            field=models.CharField(max_length=10),
        ),
    ]
